# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ce958a05c5565dc2e91e8e22a0c4d5094db06fb6a061e29427bd90279dfec694e4bc90daf2fb505a1e6cf0f58be0a68cb383cc7c91140cff8d3937f40371bdc

test:
  secret_key_base: 8284d753fda103e975270a575a6768f14526c39cd88862cc27d271c39f00d4a676afb2e837f1a4946131675956eae0f8f5b0890225a9a96fbd40c2b06d909e09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
